version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/glean"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/automation"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/samples/browser/web"
    schedule:
      interval: "monthly"
